class Amplifier:
    def on(self): ...
    def set_volume(self, v): ...
class Lights:
    def dim(self, pct): ...
class Projector:
    def on(self): ...
    def wide(self): ...
class StreamingBox:
    def play(self, title): ...